### ISSUE TITLE
where to download model files and the context encoding

### ISSUE THREAD

**Issue by liudongliangHI** [heathcliff233/fastMSA#1]
Thanks for sharing the code for fastMSA.
as you said，
download the model pth file and set the path path_to_model
download the context encoding to directory path_to_ctx, the provided ctx encoding is based on UniRef90 2018.3, change it into two-line format and set the path as path_to_ur90.

but, where to download model files and the context encoding?I see that the model file is imported from local, does that mean I need to train the model myself?

**Comment by heathcliff233** [comment]
Hello, thank you for your interest in fastMSA! Actually, fastMSA paper is undergoing major revision and I am currently refractoring the code. The new repo structure will be very different, so I would recommend waiting for a couple of weeks for the latest version. 
But if urgent, you may download the model checkpoint [here](https://drive.google.com/file/d/1YGuWO-iMsbmH1t36Fxf4gLJGH9B-EB5l/view?usp=sharing). The context encoding could be generated using scripts [here](https://github.com/heathcliff233/fastMSA/blob/master/dense_encode/generate_vec_one.py), please prepare around 700GB disk space for storage. Sorry for the inconvenience.

**Comment by liudongliangHI** [comment]
Thank you, looking forward to your new work.
